


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
 <link rel="icon" type="image/vnd.microsoft.icon" href="http://www.gstatic.com/codesite/ph/images/phosting.ico">
 
 <script type="text/javascript">
 
 
 
 var codesite_token = "b8b0f64c47b06eae0c45d2f2a738c564";
 
 
 var logged_in_user_email = "robson.medeiros@gmail.com";
 
 
 var relative_base_url = "";
 
 </script>
 
 
 <title>script.SQL - 
 filescontrol -
 
 Project Hosting on Google Code</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
 
 <link type="text/css" rel="stylesheet" href="http://www.gstatic.com/codesite/ph/1274223301709965370/css/ph_core.css">
 
 <link type="text/css" rel="stylesheet" href="http://www.gstatic.com/codesite/ph/1274223301709965370/css/ph_detail.css" >
 
 
 <link type="text/css" rel="stylesheet" href="http://www.gstatic.com/codesite/ph/1274223301709965370/css/d_sb_20080522.css" >
 
 
 
<!--[if IE]>
 <link type="text/css" rel="stylesheet" href="http://www.gstatic.com/codesite/ph/1274223301709965370/css/d_ie.css" >
<![endif]-->
 <style type="text/css">
 .menuIcon.off { background: no-repeat url(http://www.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 -42px }
 .menuIcon.on { background: no-repeat url(http://www.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 -28px }
 .menuIcon.down { background: no-repeat url(http://www.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 0; }
 </style>
</head>
<body class="t4">
 <script type="text/javascript">
 var _gaq = _gaq || [];
 _gaq.push(
 ['siteTracker._setAccount', 'UA-18071-1'],
 ['siteTracker._trackPageview']);
 
 (function() {
 var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
 ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
 (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
 </script>
 <div id="gaia">
 
 <span>
 
 
 <b>robson.medeiros@gmail.com</b>
 
 
 | <a href="/u/robson.medeiros/" id="projects-dropdown" onclick="return false;"
 ><u>My favorites</u> <small>&#9660;</small></a>
 | <a href="/u/robson.medeiros/" onclick="_CS_click('/gb/ph/profile');" 
 title="Profile, Updates, and Settings"
 ><u>Profile</u></a>
 | <a href="https://www.google.com/accounts/Logout?continue=http%3A%2F%2Fcode.google.com%2Fp%2Ffilescontrol%2Fsource%2Fbrowse%2Ftrunk%2FController%2FDataBase%2Fscript.SQL" 
 onclick="_CS_click('/gb/ph/signout');"
 ><u>Sign out</u></a>
 
 </span>

 </div>
 <div class="gbh" style="left: 0pt;"></div>
 <div class="gbh" style="right: 0pt;"></div>
 
 
 <div style="height: 1px"></div>
<!--[if IE 6]>
<div style="text-align:center;">
Support browsers that contribute to open source, try <a href="http://www.firefox.com">Firefox</a> or <a href="http://www.google.com/chrome">Google Chrome</a>.
</div>
<![endif]-->



 <table style="padding:0px; margin: 20px 0px 0px 0px; width:100%" cellpadding="0" cellspacing="0">
 <tr style="height: 58px;">
 
 <td style="width: 55px; text-align:center;">
 <a href="/p/filescontrol/">
 
 <img src="http://www.gstatic.com/codesite/ph/images/defaultlogo.png" alt="Logo">
 
 </a>
 </td>
 
 <td style="padding-left: 0.5em">
 
 <div id="pname" style="margin: 0px 0px -3px 0px">
 <a href="/p/filescontrol/" style="text-decoration:none; color:#000">filescontrol</a>
 
 </div>
 <div id="psum">
 <i><a id="project_summary_link" href="/p/filescontrol/" style="text-decoration:none; color:#000">Controlador de Arquivos Distribuídos</a></i>
 </div>
 
 </td>
 <td style="white-space:nowrap;text-align:right">
 
 <form action="/hosting/search">
 <input size="30" name="q" value="">
 <input type="submit" name="projectsearch" value="Search projects" >
 </form>
 
 </tr>
 </table>


 
<table id="mt" cellspacing="0" cellpadding="0" width="100%" border="0">
 <tr>
 <th onclick="if (!cancelBubble) _go('/p/filescontrol/');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/filescontrol/">Project&nbsp;Home</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 
 
 <th onclick="if (!cancelBubble) _go('/p/filescontrol/downloads/list');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/filescontrol/downloads/list">Downloads</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 
 
 
 <th onclick="if (!cancelBubble) _go('/p/filescontrol/w/list');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/filescontrol/w/list">Wiki</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 
 
 
 <th onclick="if (!cancelBubble) _go('/p/filescontrol/issues/list');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/filescontrol/issues/list">Issues</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 
 
 
 <th onclick="if (!cancelBubble) _go('/p/filescontrol/source/checkout');">
 <div class="tab active">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/filescontrol/source/checkout">Source</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 <th onclick="if (!cancelBubble) _go('/p/filescontrol/admin');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/filescontrol/admin">Administer</a>
 </div>
 </div>
 </th>
 <td width="100%">&nbsp;</td>
 </tr>
</table>
<table cellspacing="0" cellpadding="0" width="100%" align="center" border="0" class="st">
 <tr>
 
 
 
 
 
 
 <td>
 <div class="st2">
 <div class="isf">
 
 
 
 <span class="inst1"><a href="/p/filescontrol/source/checkout">Checkout</a></span> |
 <span class="inst2"><a href="/p/filescontrol/source/browse/">Browse</a></span> |
 <span class="inst3"><a href="/p/filescontrol/source/list">Changes</a></span> |
 
 <form action="http://www.google.com/codesearch" method="get" style="display:inline"
 onsubmit="document.getElementById('codesearchq').value = document.getElementById('origq').value + ' package:http://filescontrol\\.googlecode\\.com'">
 <input type="hidden" name="q" id="codesearchq" value="">
 <input maxlength="2048" size="38" id="origq" name="origq" value="" title="Google Code Search" style="font-size:92%">&nbsp;<input type="submit" value="Search Trunk" name="btnG" style="font-size:92%">
 
  |
 <a href="/p/filescontrol/issues/entry?show=review&former=sourcelist">Request code review</a>
 
 
 </form>
 </div>
</div>

 </td>
 
 
 
 <td height="4" align="right" valign="top" class="bevel-right">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 </td>
 </tr>
</table>
<script type="text/javascript">
 var cancelBubble = false;
 function _go(url) { document.location = url; }
</script>


<div id="maincol"
 
>

 
<!-- IE -->




<div class="expand">


<style type="text/css">
 #file_flipper { display: inline; float: right; white-space: nowrap; }
 #file_flipper.hidden { display: none; }
 #file_flipper .pagelink { color: #0000CC; text-decoration: underline; }
 #file_flipper #visiblefiles { padding-left: 0.5em; padding-right: 0.5em; }
</style>
<div id="nav_and_rev" class="heading">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner" id="bub">
 <div class="bub-top">
 <div class="pagination" style="margin-left: 2em">
 <table cellpadding="0" cellspacing="0" class="flipper">
 <tbody>
 <tr>
 
 <td>
 <ul class="leftside">
 
 <li><a href="/p/filescontrol/source/browse/trunk/Controller/DataBase/script.SQL?r=79" title="Previous">&lsaquo;r79</a></li>
 
 </ul>
 </td>
 
 <td><b>r93</b></td>
 
 </tr>
 </tbody>
 </table>
 </div>
 
 <div class="" style="vertical-align: top">
 <div class="src_crumbs src_nav">
 <strong class="src_nav">Source path:&nbsp;</strong>
 <span id="crumb_root">
 
 <a href="/p/filescontrol/source/browse/">svn</a>/&nbsp;</span>
 <span id="crumb_links" class="ifClosed"><a href="/p/filescontrol/source/browse/trunk/">trunk</a><span class="sp">/&nbsp;</span><a href="/p/filescontrol/source/browse/trunk/Controller/">Controller</a><span class="sp">/&nbsp;</span><a href="/p/filescontrol/source/browse/trunk/Controller/DataBase/">DataBase</a><span class="sp">/&nbsp;</span>script.SQL</span>
 
 
 </div>
 
 </div>
 <div style="clear:both"></div>
 </div>
 </div>
</div>

<style type="text/css">
 
  tr.inline_comment {
 background: #fff;
 vertical-align: top;
 }
 div.draft, div.published {
 padding: .3em;
 border: 1px solid #999; 
 margin-bottom: .1em;
 font-family: arial, sans-serif;
 max-width: 60em;
 }
 div.draft {
 background: #ffa;
 } 
 div.published {
 background: #e5ecf9;
 }
 div.published .body, div.draft .body {
 padding: .5em .1em .1em .1em;
 max-width: 60em;
 white-space: pre-wrap;
 white-space: -moz-pre-wrap;
 white-space: -pre-wrap;
 white-space: -o-pre-wrap;
 word-wrap: break-word;
 }
 div.draft .actions {
 margin-left: 1em;
 font-size: 90%;
 }
 div.draft form {
 padding: .5em .5em .5em 0;
 }
 div.draft textarea, div.published textarea {
 width: 95%;
 height: 10em;
 font-family: arial, sans-serif;
 margin-bottom: .5em;
 }


 
 .nocursor, .nocursor td, .cursor_hidden, .cursor_hidden td {
 background-color: white;
 height: 2px;
 }
 .cursor, .cursor td {
 background-color: darkblue;
 height: 2px;
 display: '';
 }

</style>
<div class="fc">
 
 
 
<style type="text/css">
.undermouse span { 
 background-image: url(http://www.gstatic.com/codesite/ph/images/comments.gif); }
</style>
<table class="opened" id="review_comment_area" 
onmouseout="gutterOut()"><tr>
<td id="nums">
<pre><table width="100%"><tr class="nocursor"><td></td></tr></table></pre>

<pre><table width="100%" id="nums_table_0"><tr id="gr_svn82_1"

 onmouseover="gutterOver(1)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',1);">&nbsp;</span
></td><td id="1"><a href="#1">1</a></td></tr
><tr id="gr_svn82_2"

 onmouseover="gutterOver(2)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',2);">&nbsp;</span
></td><td id="2"><a href="#2">2</a></td></tr
><tr id="gr_svn82_3"

 onmouseover="gutterOver(3)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',3);">&nbsp;</span
></td><td id="3"><a href="#3">3</a></td></tr
><tr id="gr_svn82_4"

 onmouseover="gutterOver(4)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',4);">&nbsp;</span
></td><td id="4"><a href="#4">4</a></td></tr
><tr id="gr_svn82_5"

 onmouseover="gutterOver(5)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',5);">&nbsp;</span
></td><td id="5"><a href="#5">5</a></td></tr
><tr id="gr_svn82_6"

 onmouseover="gutterOver(6)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',6);">&nbsp;</span
></td><td id="6"><a href="#6">6</a></td></tr
><tr id="gr_svn82_7"

 onmouseover="gutterOver(7)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',7);">&nbsp;</span
></td><td id="7"><a href="#7">7</a></td></tr
><tr id="gr_svn82_8"

 onmouseover="gutterOver(8)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',8);">&nbsp;</span
></td><td id="8"><a href="#8">8</a></td></tr
><tr id="gr_svn82_9"

 onmouseover="gutterOver(9)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',9);">&nbsp;</span
></td><td id="9"><a href="#9">9</a></td></tr
><tr id="gr_svn82_10"

 onmouseover="gutterOver(10)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',10);">&nbsp;</span
></td><td id="10"><a href="#10">10</a></td></tr
><tr id="gr_svn82_11"

 onmouseover="gutterOver(11)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',11);">&nbsp;</span
></td><td id="11"><a href="#11">11</a></td></tr
><tr id="gr_svn82_12"

 onmouseover="gutterOver(12)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',12);">&nbsp;</span
></td><td id="12"><a href="#12">12</a></td></tr
><tr id="gr_svn82_13"

 onmouseover="gutterOver(13)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',13);">&nbsp;</span
></td><td id="13"><a href="#13">13</a></td></tr
><tr id="gr_svn82_14"

 onmouseover="gutterOver(14)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',14);">&nbsp;</span
></td><td id="14"><a href="#14">14</a></td></tr
><tr id="gr_svn82_15"

 onmouseover="gutterOver(15)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',15);">&nbsp;</span
></td><td id="15"><a href="#15">15</a></td></tr
><tr id="gr_svn82_16"

 onmouseover="gutterOver(16)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',16);">&nbsp;</span
></td><td id="16"><a href="#16">16</a></td></tr
><tr id="gr_svn82_17"

 onmouseover="gutterOver(17)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',17);">&nbsp;</span
></td><td id="17"><a href="#17">17</a></td></tr
><tr id="gr_svn82_18"

 onmouseover="gutterOver(18)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',18);">&nbsp;</span
></td><td id="18"><a href="#18">18</a></td></tr
><tr id="gr_svn82_19"

 onmouseover="gutterOver(19)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',19);">&nbsp;</span
></td><td id="19"><a href="#19">19</a></td></tr
><tr id="gr_svn82_20"

 onmouseover="gutterOver(20)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',20);">&nbsp;</span
></td><td id="20"><a href="#20">20</a></td></tr
><tr id="gr_svn82_21"

 onmouseover="gutterOver(21)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',21);">&nbsp;</span
></td><td id="21"><a href="#21">21</a></td></tr
><tr id="gr_svn82_22"

 onmouseover="gutterOver(22)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',22);">&nbsp;</span
></td><td id="22"><a href="#22">22</a></td></tr
><tr id="gr_svn82_23"

 onmouseover="gutterOver(23)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',23);">&nbsp;</span
></td><td id="23"><a href="#23">23</a></td></tr
><tr id="gr_svn82_24"

 onmouseover="gutterOver(24)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',24);">&nbsp;</span
></td><td id="24"><a href="#24">24</a></td></tr
><tr id="gr_svn82_25"

 onmouseover="gutterOver(25)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',25);">&nbsp;</span
></td><td id="25"><a href="#25">25</a></td></tr
><tr id="gr_svn82_26"

 onmouseover="gutterOver(26)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',26);">&nbsp;</span
></td><td id="26"><a href="#26">26</a></td></tr
><tr id="gr_svn82_27"

 onmouseover="gutterOver(27)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',27);">&nbsp;</span
></td><td id="27"><a href="#27">27</a></td></tr
><tr id="gr_svn82_28"

 onmouseover="gutterOver(28)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',28);">&nbsp;</span
></td><td id="28"><a href="#28">28</a></td></tr
><tr id="gr_svn82_29"

 onmouseover="gutterOver(29)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',29);">&nbsp;</span
></td><td id="29"><a href="#29">29</a></td></tr
><tr id="gr_svn82_30"

 onmouseover="gutterOver(30)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',30);">&nbsp;</span
></td><td id="30"><a href="#30">30</a></td></tr
><tr id="gr_svn82_31"

 onmouseover="gutterOver(31)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',31);">&nbsp;</span
></td><td id="31"><a href="#31">31</a></td></tr
><tr id="gr_svn82_32"

 onmouseover="gutterOver(32)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',32);">&nbsp;</span
></td><td id="32"><a href="#32">32</a></td></tr
><tr id="gr_svn82_33"

 onmouseover="gutterOver(33)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',33);">&nbsp;</span
></td><td id="33"><a href="#33">33</a></td></tr
><tr id="gr_svn82_34"

 onmouseover="gutterOver(34)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',34);">&nbsp;</span
></td><td id="34"><a href="#34">34</a></td></tr
><tr id="gr_svn82_35"

 onmouseover="gutterOver(35)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',35);">&nbsp;</span
></td><td id="35"><a href="#35">35</a></td></tr
><tr id="gr_svn82_36"

 onmouseover="gutterOver(36)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',36);">&nbsp;</span
></td><td id="36"><a href="#36">36</a></td></tr
><tr id="gr_svn82_37"

 onmouseover="gutterOver(37)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',37);">&nbsp;</span
></td><td id="37"><a href="#37">37</a></td></tr
><tr id="gr_svn82_38"

 onmouseover="gutterOver(38)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',38);">&nbsp;</span
></td><td id="38"><a href="#38">38</a></td></tr
><tr id="gr_svn82_39"

 onmouseover="gutterOver(39)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',39);">&nbsp;</span
></td><td id="39"><a href="#39">39</a></td></tr
><tr id="gr_svn82_40"

 onmouseover="gutterOver(40)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',40);">&nbsp;</span
></td><td id="40"><a href="#40">40</a></td></tr
><tr id="gr_svn82_41"

 onmouseover="gutterOver(41)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',41);">&nbsp;</span
></td><td id="41"><a href="#41">41</a></td></tr
><tr id="gr_svn82_42"

 onmouseover="gutterOver(42)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',42);">&nbsp;</span
></td><td id="42"><a href="#42">42</a></td></tr
><tr id="gr_svn82_43"

 onmouseover="gutterOver(43)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',43);">&nbsp;</span
></td><td id="43"><a href="#43">43</a></td></tr
><tr id="gr_svn82_44"

 onmouseover="gutterOver(44)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',44);">&nbsp;</span
></td><td id="44"><a href="#44">44</a></td></tr
><tr id="gr_svn82_45"

 onmouseover="gutterOver(45)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',45);">&nbsp;</span
></td><td id="45"><a href="#45">45</a></td></tr
><tr id="gr_svn82_46"

 onmouseover="gutterOver(46)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',46);">&nbsp;</span
></td><td id="46"><a href="#46">46</a></td></tr
><tr id="gr_svn82_47"

 onmouseover="gutterOver(47)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',47);">&nbsp;</span
></td><td id="47"><a href="#47">47</a></td></tr
><tr id="gr_svn82_48"

 onmouseover="gutterOver(48)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',48);">&nbsp;</span
></td><td id="48"><a href="#48">48</a></td></tr
><tr id="gr_svn82_49"

 onmouseover="gutterOver(49)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',49);">&nbsp;</span
></td><td id="49"><a href="#49">49</a></td></tr
><tr id="gr_svn82_50"

 onmouseover="gutterOver(50)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',50);">&nbsp;</span
></td><td id="50"><a href="#50">50</a></td></tr
><tr id="gr_svn82_51"

 onmouseover="gutterOver(51)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',51);">&nbsp;</span
></td><td id="51"><a href="#51">51</a></td></tr
><tr id="gr_svn82_52"

 onmouseover="gutterOver(52)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',52);">&nbsp;</span
></td><td id="52"><a href="#52">52</a></td></tr
><tr id="gr_svn82_53"

 onmouseover="gutterOver(53)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',53);">&nbsp;</span
></td><td id="53"><a href="#53">53</a></td></tr
><tr id="gr_svn82_54"

 onmouseover="gutterOver(54)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',54);">&nbsp;</span
></td><td id="54"><a href="#54">54</a></td></tr
><tr id="gr_svn82_55"

 onmouseover="gutterOver(55)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',55);">&nbsp;</span
></td><td id="55"><a href="#55">55</a></td></tr
><tr id="gr_svn82_56"

 onmouseover="gutterOver(56)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',56);">&nbsp;</span
></td><td id="56"><a href="#56">56</a></td></tr
><tr id="gr_svn82_57"

 onmouseover="gutterOver(57)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',57);">&nbsp;</span
></td><td id="57"><a href="#57">57</a></td></tr
><tr id="gr_svn82_58"

 onmouseover="gutterOver(58)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',58);">&nbsp;</span
></td><td id="58"><a href="#58">58</a></td></tr
><tr id="gr_svn82_59"

 onmouseover="gutterOver(59)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',59);">&nbsp;</span
></td><td id="59"><a href="#59">59</a></td></tr
><tr id="gr_svn82_60"

 onmouseover="gutterOver(60)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',60);">&nbsp;</span
></td><td id="60"><a href="#60">60</a></td></tr
><tr id="gr_svn82_61"

 onmouseover="gutterOver(61)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',61);">&nbsp;</span
></td><td id="61"><a href="#61">61</a></td></tr
><tr id="gr_svn82_62"

 onmouseover="gutterOver(62)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',62);">&nbsp;</span
></td><td id="62"><a href="#62">62</a></td></tr
><tr id="gr_svn82_63"

 onmouseover="gutterOver(63)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',63);">&nbsp;</span
></td><td id="63"><a href="#63">63</a></td></tr
><tr id="gr_svn82_64"

 onmouseover="gutterOver(64)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',64);">&nbsp;</span
></td><td id="64"><a href="#64">64</a></td></tr
><tr id="gr_svn82_65"

 onmouseover="gutterOver(65)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',65);">&nbsp;</span
></td><td id="65"><a href="#65">65</a></td></tr
><tr id="gr_svn82_66"

 onmouseover="gutterOver(66)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',66);">&nbsp;</span
></td><td id="66"><a href="#66">66</a></td></tr
><tr id="gr_svn82_67"

 onmouseover="gutterOver(67)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',67);">&nbsp;</span
></td><td id="67"><a href="#67">67</a></td></tr
><tr id="gr_svn82_68"

 onmouseover="gutterOver(68)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',68);">&nbsp;</span
></td><td id="68"><a href="#68">68</a></td></tr
><tr id="gr_svn82_69"

 onmouseover="gutterOver(69)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',69);">&nbsp;</span
></td><td id="69"><a href="#69">69</a></td></tr
><tr id="gr_svn82_70"

 onmouseover="gutterOver(70)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',70);">&nbsp;</span
></td><td id="70"><a href="#70">70</a></td></tr
><tr id="gr_svn82_71"

 onmouseover="gutterOver(71)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',71);">&nbsp;</span
></td><td id="71"><a href="#71">71</a></td></tr
><tr id="gr_svn82_72"

 onmouseover="gutterOver(72)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',72);">&nbsp;</span
></td><td id="72"><a href="#72">72</a></td></tr
><tr id="gr_svn82_73"

 onmouseover="gutterOver(73)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',73);">&nbsp;</span
></td><td id="73"><a href="#73">73</a></td></tr
><tr id="gr_svn82_74"

 onmouseover="gutterOver(74)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',74);">&nbsp;</span
></td><td id="74"><a href="#74">74</a></td></tr
><tr id="gr_svn82_75"

 onmouseover="gutterOver(75)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',75);">&nbsp;</span
></td><td id="75"><a href="#75">75</a></td></tr
><tr id="gr_svn82_76"

 onmouseover="gutterOver(76)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',76);">&nbsp;</span
></td><td id="76"><a href="#76">76</a></td></tr
><tr id="gr_svn82_77"

 onmouseover="gutterOver(77)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',77);">&nbsp;</span
></td><td id="77"><a href="#77">77</a></td></tr
><tr id="gr_svn82_78"

 onmouseover="gutterOver(78)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',78);">&nbsp;</span
></td><td id="78"><a href="#78">78</a></td></tr
><tr id="gr_svn82_79"

 onmouseover="gutterOver(79)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',79);">&nbsp;</span
></td><td id="79"><a href="#79">79</a></td></tr
><tr id="gr_svn82_80"

 onmouseover="gutterOver(80)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',80);">&nbsp;</span
></td><td id="80"><a href="#80">80</a></td></tr
><tr id="gr_svn82_81"

 onmouseover="gutterOver(81)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',81);">&nbsp;</span
></td><td id="81"><a href="#81">81</a></td></tr
><tr id="gr_svn82_82"

 onmouseover="gutterOver(82)"

><td><span title="Add comment" onclick="CR_startEdit('svn82',82);">&nbsp;</span
></td><td id="82"><a href="#82">82</a></td></tr
></table></pre>

<pre><table width="100%"><tr class="nocursor"><td></td></tr></table></pre>
</td>
<td id="lines">
<pre class="prettyprint"><table width="100%"><tr class="cursor_stop cursor_hidden"><td></td></tr></table></pre>

<pre class="prettyprint lang-sql"><table id="src_table_0"><tr
id=sl_svn82_1

 onmouseover="gutterOver(1)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_2

 onmouseover="gutterOver(2)"

><td class="source">-- Create tables section -------------------------------------------------<br></td></tr
><tr
id=sl_svn82_3

 onmouseover="gutterOver(3)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_4

 onmouseover="gutterOver(4)"

><td class="source">-- Table FileSD<br></td></tr
><tr
id=sl_svn82_5

 onmouseover="gutterOver(5)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_6

 onmouseover="gutterOver(6)"

><td class="source">CREATE TABLE &quot;file_sd&quot;(<br></td></tr
><tr
id=sl_svn82_7

 onmouseover="gutterOver(7)"

><td class="source"> &quot;id&quot; Serial NOT NULL,<br></td></tr
><tr
id=sl_svn82_8

 onmouseover="gutterOver(8)"

><td class="source"> &quot;name&quot; Varchar NOT NULL,<br></td></tr
><tr
id=sl_svn82_9

 onmouseover="gutterOver(9)"

><td class="source"> &quot;size&quot; Integer NOT NULL<br></td></tr
><tr
id=sl_svn82_10

 onmouseover="gutterOver(10)"

><td class="source">)<br></td></tr
><tr
id=sl_svn82_11

 onmouseover="gutterOver(11)"

><td class="source">WITHOUT OIDS<br></td></tr
><tr
id=sl_svn82_12

 onmouseover="gutterOver(12)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_13

 onmouseover="gutterOver(13)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_14

 onmouseover="gutterOver(14)"

><td class="source">-- Add keys for table FileSD<br></td></tr
><tr
id=sl_svn82_15

 onmouseover="gutterOver(15)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_16

 onmouseover="gutterOver(16)"

><td class="source">ALTER TABLE &quot;file_sd&quot; ADD CONSTRAINT &quot;Key1&quot; PRIMARY KEY (&quot;id&quot;)<br></td></tr
><tr
id=sl_svn82_17

 onmouseover="gutterOver(17)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_18

 onmouseover="gutterOver(18)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_19

 onmouseover="gutterOver(19)"

><td class="source">ALTER TABLE &quot;file_sd&quot; ADD CONSTRAINT &quot;id&quot; UNIQUE (&quot;id&quot;)<br></td></tr
><tr
id=sl_svn82_20

 onmouseover="gutterOver(20)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_21

 onmouseover="gutterOver(21)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_22

 onmouseover="gutterOver(22)"

><td class="source">-- Table Node<br></td></tr
><tr
id=sl_svn82_23

 onmouseover="gutterOver(23)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_24

 onmouseover="gutterOver(24)"

><td class="source">CREATE TABLE &quot;node&quot;(<br></td></tr
><tr
id=sl_svn82_25

 onmouseover="gutterOver(25)"

><td class="source"> &quot;ip&quot; Varchar NOT NULL,<br></td></tr
><tr
id=sl_svn82_26

 onmouseover="gutterOver(26)"

><td class="source"> &quot;port&quot; Integer NOT NULL,<br></td></tr
><tr
id=sl_svn82_27

 onmouseover="gutterOver(27)"

><td class="source"> &quot;ativo&quot; Boolean NOT NULL,<br></td></tr
><tr
id=sl_svn82_28

 onmouseover="gutterOver(28)"

><td class="source"> &quot;requisicoes&quot; Integer NOT NULL<br></td></tr
><tr
id=sl_svn82_29

 onmouseover="gutterOver(29)"

><td class="source">)<br></td></tr
><tr
id=sl_svn82_30

 onmouseover="gutterOver(30)"

><td class="source">WITHOUT OIDS<br></td></tr
><tr
id=sl_svn82_31

 onmouseover="gutterOver(31)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_32

 onmouseover="gutterOver(32)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_33

 onmouseover="gutterOver(33)"

><td class="source">-- Add keys for table Node<br></td></tr
><tr
id=sl_svn82_34

 onmouseover="gutterOver(34)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_35

 onmouseover="gutterOver(35)"

><td class="source">ALTER TABLE &quot;node&quot; ADD CONSTRAINT &quot;Key2&quot; PRIMARY KEY (&quot;ip&quot;,&quot;port&quot;)<br></td></tr
><tr
id=sl_svn82_36

 onmouseover="gutterOver(36)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_37

 onmouseover="gutterOver(37)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_38

 onmouseover="gutterOver(38)"

><td class="source">-- Table Chunk<br></td></tr
><tr
id=sl_svn82_39

 onmouseover="gutterOver(39)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_40

 onmouseover="gutterOver(40)"

><td class="source">CREATE TABLE &quot;chunk&quot;(<br></td></tr
><tr
id=sl_svn82_41

 onmouseover="gutterOver(41)"

><td class="source"> &quot;id&quot; Serial NOT NULL,<br></td></tr
><tr
id=sl_svn82_42

 onmouseover="gutterOver(42)"

><td class="source"> &quot;file_id&quot; Integer NOT NULL<br></td></tr
><tr
id=sl_svn82_43

 onmouseover="gutterOver(43)"

><td class="source">)<br></td></tr
><tr
id=sl_svn82_44

 onmouseover="gutterOver(44)"

><td class="source">WITHOUT OIDS<br></td></tr
><tr
id=sl_svn82_45

 onmouseover="gutterOver(45)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_46

 onmouseover="gutterOver(46)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_47

 onmouseover="gutterOver(47)"

><td class="source">-- Add keys for table Chunk<br></td></tr
><tr
id=sl_svn82_48

 onmouseover="gutterOver(48)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_49

 onmouseover="gutterOver(49)"

><td class="source">ALTER TABLE &quot;chunk&quot; ADD CONSTRAINT &quot;Key3&quot; PRIMARY KEY (&quot;id&quot;)<br></td></tr
><tr
id=sl_svn82_50

 onmouseover="gutterOver(50)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_51

 onmouseover="gutterOver(51)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_52

 onmouseover="gutterOver(52)"

><td class="source">-- Table Node_Chunk<br></td></tr
><tr
id=sl_svn82_53

 onmouseover="gutterOver(53)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_54

 onmouseover="gutterOver(54)"

><td class="source">CREATE TABLE &quot;node_chunk&quot;(<br></td></tr
><tr
id=sl_svn82_55

 onmouseover="gutterOver(55)"

><td class="source"> &quot;id&quot; Integer NOT NULL,<br></td></tr
><tr
id=sl_svn82_56

 onmouseover="gutterOver(56)"

><td class="source"> &quot;ip&quot; Varchar NOT NULL,<br></td></tr
><tr
id=sl_svn82_57

 onmouseover="gutterOver(57)"

><td class="source"> &quot;port&quot; Integer NOT NULL<br></td></tr
><tr
id=sl_svn82_58

 onmouseover="gutterOver(58)"

><td class="source">)<br></td></tr
><tr
id=sl_svn82_59

 onmouseover="gutterOver(59)"

><td class="source">WITHOUT OIDS<br></td></tr
><tr
id=sl_svn82_60

 onmouseover="gutterOver(60)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_61

 onmouseover="gutterOver(61)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_62

 onmouseover="gutterOver(62)"

><td class="source">-- Add keys for table Node_Chunk<br></td></tr
><tr
id=sl_svn82_63

 onmouseover="gutterOver(63)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_64

 onmouseover="gutterOver(64)"

><td class="source">ALTER TABLE &quot;node_chunk&quot; ADD CONSTRAINT &quot;Key4&quot; PRIMARY KEY (&quot;id&quot;,&quot;ip&quot;,&quot;port&quot;)<br></td></tr
><tr
id=sl_svn82_65

 onmouseover="gutterOver(65)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_66

 onmouseover="gutterOver(66)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_67

 onmouseover="gutterOver(67)"

><td class="source">-- Create relationships section ------------------------------------------------- <br></td></tr
><tr
id=sl_svn82_68

 onmouseover="gutterOver(68)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_69

 onmouseover="gutterOver(69)"

><td class="source">ALTER TABLE &quot;chunk&quot; ADD CONSTRAINT &quot;Relationship3&quot; FOREIGN KEY (&quot;file_id&quot;) REFERENCES &quot;file_sd&quot; (&quot;id&quot;) ON DELETE NO ACTION ON UPDATE NO ACTION<br></td></tr
><tr
id=sl_svn82_70

 onmouseover="gutterOver(70)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_71

 onmouseover="gutterOver(71)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_72

 onmouseover="gutterOver(72)"

><td class="source">ALTER TABLE &quot;node_chunk&quot; ADD CONSTRAINT &quot;Relationship4&quot; FOREIGN KEY (&quot;id&quot;) REFERENCES &quot;chunk&quot; (&quot;id&quot;) ON DELETE NO ACTION ON UPDATE NO ACTION<br></td></tr
><tr
id=sl_svn82_73

 onmouseover="gutterOver(73)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_74

 onmouseover="gutterOver(74)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_75

 onmouseover="gutterOver(75)"

><td class="source">ALTER TABLE &quot;node_chunk&quot; ADD CONSTRAINT &quot;Relationship5&quot; FOREIGN KEY (&quot;ip&quot;, &quot;port&quot;) REFERENCES &quot;node&quot; (&quot;ip&quot;, &quot;port&quot;) ON DELETE NO ACTION ON UPDATE NO ACTION<br></td></tr
><tr
id=sl_svn82_76

 onmouseover="gutterOver(76)"

><td class="source">;<br></td></tr
><tr
id=sl_svn82_77

 onmouseover="gutterOver(77)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_78

 onmouseover="gutterOver(78)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_79

 onmouseover="gutterOver(79)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_80

 onmouseover="gutterOver(80)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_81

 onmouseover="gutterOver(81)"

><td class="source"><br></td></tr
><tr
id=sl_svn82_82

 onmouseover="gutterOver(82)"

><td class="source"><br></td></tr
></table></pre>

<pre class="prettyprint"><table width="100%"><tr class="cursor_stop cursor_hidden"><td></td></tr></table></pre>
</td>
</tr></table>
<script type="text/javascript">
 var lineNumUnderMouse = -1;
 
 function gutterOver(num) {
 gutterOut();
 var newTR = document.getElementById('gr_svn82_' + num);
 if (newTR) {
 newTR.className = 'undermouse';
 }
 lineNumUnderMouse = num;
 }
 function gutterOut() {
 if (lineNumUnderMouse != -1) {
 var oldTR = document.getElementById(
 'gr_svn82_' + lineNumUnderMouse);
 if (oldTR) {
 oldTR.className = '';
 }
 lineNumUnderMouse = -1;
 }
 }
 var numsGenState = {table_base_id: 'nums_table_'};
 var srcGenState = {table_base_id: 'src_table_'};
 var alignerRunning = false;
 var startOver = false;
 function setLineNumberHeights() {
 if (alignerRunning) {
 startOver = true;
 return;
 }
 numsGenState.chunk_id = 0;
 numsGenState.table = document.getElementById('nums_table_0');
 numsGenState.row_num = 0;
 srcGenState.chunk_id = 0;
 srcGenState.table = document.getElementById('src_table_0');
 srcGenState.row_num = 0;
 alignerRunning = true;
 continueToSetLineNumberHeights();
 }
 function rowGenerator(genState) {
 if (genState.row_num < genState.table.rows.length) {
 var currentRow = genState.table.rows[genState.row_num];
 genState.row_num++;
 return currentRow;
 }
 var newTable = document.getElementById(
 genState.table_base_id + (genState.chunk_id + 1));
 if (newTable) {
 genState.chunk_id++;
 genState.row_num = 0;
 genState.table = newTable;
 return genState.table.rows[0];
 }
 return null;
 }
 var MAX_ROWS_PER_PASS = 1000;
 function continueToSetLineNumberHeights() {
 var rowsInThisPass = 0;
 var numRow = 1;
 var srcRow = 1;
 while (numRow && srcRow && rowsInThisPass < MAX_ROWS_PER_PASS) {
 numRow = rowGenerator(numsGenState);
 srcRow = rowGenerator(srcGenState);
 rowsInThisPass++;
 if (numRow && srcRow) {
 if (numRow.offsetHeight != srcRow.offsetHeight) {
 numRow.firstChild.style.height = srcRow.offsetHeight + 'px';
 }
 }
 }
 if (rowsInThisPass >= MAX_ROWS_PER_PASS) {
 setTimeout(continueToSetLineNumberHeights, 10);
 } else {
 alignerRunning = false;
 if (startOver) {
 startOver = false;
 setTimeout(setLineNumberHeights, 500);
 }
 }
 }
 // Do 2 complete passes, because there can be races
 // between this code and prettify.
 startOver = true;
 setTimeout(setLineNumberHeights, 250);
 window.onresize = setLineNumberHeights;
</script>

 
 
 <div id="log">
 <div style="text-align:right">
 <a class="ifCollapse" href="#" onclick="_toggleMeta('', 'p', 'filescontrol', this)">Show details</a>
 <a class="ifExpand" href="#" onclick="_toggleMeta('', 'p', 'filescontrol', this)">Hide details</a>
 </div>
 <div class="ifExpand">
 
 <div class="pmeta_bubble_bg" style="border:1px solid white">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <div id="changelog">
 <p>Change log</p>
 <div>
 <a href="/p/filescontrol/source/detail?spec=svn93&r=82">r82</a>
 by davidaragao
 on Today (2 hours ago)
 &nbsp; <a href="/p/filescontrol/source/diff?spec=svn93&r=82&amp;format=side&amp;path=/trunk/Controller/DataBase/script.SQL&amp;old_path=/trunk/Controller/DataBase/script.SQL&amp;old=79">Diff</a>
 </div>
 <pre>[No log message]</pre>
 </div>
 
 
 
 
 
 
 <script type="text/javascript">
 var detail_url = '/p/filescontrol/source/detail?r=82&spec=svn93';
 var publish_url = '/p/filescontrol/source/detail?r=82&spec=svn93#publish';
 // describe the paths of this revision in javascript.
 var changed_paths = [];
 var changed_urls = [];
 
 changed_paths.push('/trunk/Controller/DataBase/script.SQL');
 changed_urls.push('/p/filescontrol/source/browse/trunk/Controller/DataBase/script.SQL?r=82&spec=svn93');
 
 var selected_path = '/trunk/Controller/DataBase/script.SQL';
 
 
 function getCurrentPageIndex() {
 for (var i = 0; i < changed_paths.length; i++) {
 if (selected_path == changed_paths[i]) {
 return i;
 }
 }
 }
 function getNextPage() {
 var i = getCurrentPageIndex();
 if (i < changed_paths.length - 1) {
 return changed_urls[i + 1];
 }
 return null;
 }
 function getPreviousPage() {
 var i = getCurrentPageIndex();
 if (i > 0) {
 return changed_urls[i - 1];
 }
 return null;
 }
 function gotoNextPage() {
 var page = getNextPage();
 if (!page) {
 page = detail_url;
 }
 window.location = page;
 }
 function gotoPreviousPage() {
 var page = getPreviousPage();
 if (!page) {
 page = detail_url;
 }
 window.location = page;
 }
 function gotoDetailPage() {
 window.location = detail_url;
 }
 function gotoPublishPage() {
 window.location = publish_url;
 }
</script>
 
 <style type="text/css">
 #review_nav {
 border-top: 3px solid white;
 padding-top: 6px;
 margin-top: 1em;
 }
 #review_nav td {
 vertical-align: middle;
 }
 #review_nav select {
 margin: .5em 0;
 }
 </style>
 <div id="review_nav">
 <table><tr><td>Go to:&nbsp;</td><td>
 <select name="files_in_rev" onchange="window.location=this.value">
 
 <option value="/p/filescontrol/source/browse/trunk/Controller/DataBase/script.SQL?r=82&amp;spec=svn93"
 selected="selected"
 >...k/Controller/DataBase/script.SQL</option>
 
 </select>
 </td></tr></table>
 
 
 
 <div id="review_instr" class="closed">
 <a class="ifOpened" href="/p/filescontrol/source/detail?r=82&spec=svn93#publish">Publish your comments</a>
 <div class="ifClosed">Double click a line to add a comment</div>
 </div>
 
 </div>
 
 
 </div>
 <div class="round1"></div>
 <div class="round2"></div>
 <div class="round4"></div>
 </div>
 <div class="pmeta_bubble_bg" style="border:1px solid white">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <div id="older_bubble">
 <p>Older revisions</p>
 
 
 <div class="closed" style="margin-bottom:3px;" >
 <img class="ifClosed" onclick="_toggleHidden(this)" src="http://www.gstatic.com/codesite/ph/images/plus.gif" >
 <img class="ifOpened" onclick="_toggleHidden(this)" src="http://www.gstatic.com/codesite/ph/images/minus.gif" >
 <a href="/p/filescontrol/source/detail?spec=svn93&r=79">r79</a>
 by davidaragao
 on Yesterday (22 hours ago)
 &nbsp; <a href="/p/filescontrol/source/diff?spec=svn93&r=79&amp;format=side&amp;path=/trunk/Controller/DataBase/script.SQL&amp;old_path=/trunk/Controller/DataBase/script.SQL&amp;old=74">Diff</a>
 <br>
 <pre class="ifOpened">[No log message]</pre>
 </div>
 
 <div class="closed" style="margin-bottom:3px;" >
 <img class="ifClosed" onclick="_toggleHidden(this)" src="http://www.gstatic.com/codesite/ph/images/plus.gif" >
 <img class="ifOpened" onclick="_toggleHidden(this)" src="http://www.gstatic.com/codesite/ph/images/minus.gif" >
 <a href="/p/filescontrol/source/detail?spec=svn93&r=74">r74</a>
 by salvinhu
 on Yesterday (29 hours ago)
 &nbsp; <a href="/p/filescontrol/source/diff?spec=svn93&r=74&amp;format=side&amp;path=/trunk/Controller/DataBase/script.SQL&amp;old_path=/trunk/Controller/DataBase/script.SQL&amp;old=72">Diff</a>
 <br>
 <pre class="ifOpened">//mudado de numRequisicoes para estado
// flag pra indicar se nó esta ativo
ou não</pre>
 </div>
 
 <div class="closed" style="margin-bottom:3px;" >
 <img class="ifClosed" onclick="_toggleHidden(this)" src="http://www.gstatic.com/codesite/ph/images/plus.gif" >
 <img class="ifOpened" onclick="_toggleHidden(this)" src="http://www.gstatic.com/codesite/ph/images/minus.gif" >
 <a href="/p/filescontrol/source/detail?spec=svn93&r=72">r72</a>
 by robson.medeiros
 on Jul 03 (45 hours ago)
 &nbsp; <a href="/p/filescontrol/source/diff?spec=svn93&r=72&amp;format=side&amp;path=/trunk/Controller/DataBase/script.SQL&amp;old_path=/trunk/Controller/DataBase/script.SQL&amp;old=71">Diff</a>
 <br>
 <pre class="ifOpened">[No log message]</pre>
 </div>
 
 
 <a href="/p/filescontrol/source/list?path=/trunk/Controller/DataBase/script.SQL&start=82">All revisions of this file</a>
 </div>
 </div>
 <div class="round1"></div>
 <div class="round2"></div>
 <div class="round4"></div>
 </div>
 <div class="pmeta_bubble_bg" style="border:1px solid white">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <div id="fileinfo_bubble">
 <p>File info</p>
 
 <div>Size: 1700 bytes,
 82 lines</div>
 
 <div><a href="http://filescontrol.googlecode.com/svn/trunk/Controller/DataBase/script.SQL">View raw file</a></div>
 </div>
 
 </div>
 <div class="round1"></div>
 <div class="round2"></div>
 <div class="round4"></div>
 </div>
 </div>
 </div>


</div>
</div>

 <script src="http://www.gstatic.com/codesite/ph/1274223301709965370/js/prettify/prettify.js"></script>

 <script src="http://www.gstatic.com/codesite/ph/1274223301709965370/js/prettify/lang-sql.js"></script>

<script type="text/javascript">prettyPrint();</script>

<script src="http://www.gstatic.com/codesite/ph/1274223301709965370/js/source_file_scripts.js"></script>

 <script type="text/javascript" src="http://kibbles.googlecode.com/files/kibbles-1.3.1.comp.js"></script>
 <script type="text/javascript">
 var lastStop = null;
 var initilized = false;
 
 function updateCursor(next, prev) {
 if (prev && prev.element) {
 prev.element.className = 'cursor_stop cursor_hidden';
 }
 if (next && next.element) {
 next.element.className = 'cursor_stop cursor';
 lastStop = next.index;
 }
 }
 
 function pubRevealed(data) {
 updateCursorForCell(data.cellId, 'cursor_stop cursor_hidden');
 if (initilized) {
 reloadCursors();
 }
 }
 
 function draftRevealed(data) {
 updateCursorForCell(data.cellId, 'cursor_stop cursor_hidden');
 if (initilized) {
 reloadCursors();
 }
 }
 
 function draftDestroyed(data) {
 updateCursorForCell(data.cellId, 'nocursor');
 if (initilized) {
 reloadCursors();
 }
 }
 function reloadCursors() {
 kibbles.skipper.reset();
 loadCursors();
 if (lastStop != null) {
 kibbles.skipper.setCurrentStop(lastStop);
 }
 }
 // possibly the simplest way to insert any newly added comments
 // is to update the class of the corresponding cursor row,
 // then refresh the entire list of rows.
 function updateCursorForCell(cellId, className) {
 var cell = document.getElementById(cellId);
 // we have to go two rows back to find the cursor location
 var row = getPreviousElement(cell.parentNode);
 row.className = className;
 }
 // returns the previous element, ignores text nodes.
 function getPreviousElement(e) {
 var element = e.previousSibling;
 if (element.nodeType == 3) {
 element = element.previousSibling;
 }
 if (element && element.tagName) {
 return element;
 }
 }
 function loadCursors() {
 // register our elements with skipper
 var elements = CR_getElements('*', 'cursor_stop');
 var len = elements.length;
 for (var i = 0; i < len; i++) {
 var element = elements[i]; 
 element.className = 'cursor_stop cursor_hidden';
 kibbles.skipper.append(element);
 }
 }
 function toggleComments() {
 CR_toggleCommentDisplay();
 reloadCursors();
 }
 function keysOnLoadHandler() {
 // setup skipper
 kibbles.skipper.addStopListener(
 kibbles.skipper.LISTENER_TYPE.PRE, updateCursor);
 // Set the 'offset' option to return the middle of the client area
 // an option can be a static value, or a callback
 kibbles.skipper.setOption('padding_top', 50);
 // Set the 'offset' option to return the middle of the client area
 // an option can be a static value, or a callback
 kibbles.skipper.setOption('padding_bottom', 100);
 // Register our keys
 kibbles.skipper.addFwdKey("n");
 kibbles.skipper.addRevKey("p");
 kibbles.keys.addKeyPressListener(
 'u', function() { window.location = detail_url; });
 kibbles.keys.addKeyPressListener(
 'r', function() { window.location = detail_url + '#publish'; });
 
 kibbles.keys.addKeyPressListener('j', gotoNextPage);
 kibbles.keys.addKeyPressListener('k', gotoPreviousPage);
 
 
 kibbles.keys.addKeyPressListener('h', toggleComments);
 
 }
 window.onload = function() {keysOnLoadHandler();};
 </script>

<!-- code review support -->
<script src="http://www.gstatic.com/codesite/ph/1274223301709965370/js/code_review_scripts.js"></script>
<script type="text/javascript">
 
 // the comment form template
 var form = '<div class="draft"><div class="header"><span class="title">Draft comment:</span></div>' +
 '<div class="body"><form onsubmit="return false;"><textarea id="$ID">$BODY</textarea><br>$ACTIONS</form></div>' +
 '</div>';
 // the comment "plate" template used for both draft and published comment "plates".
 var draft_comment = '<div class="draft" ondblclick="$ONDBLCLICK">' +
 '<div class="header"><span class="title">Draft comment:</span><span class="actions">$ACTIONS</span></div>' +
 '<pre id="$ID" class="body">$BODY</pre>' +
 '</div>';
 var published_comment = '<div class="published">' +
 '<div class="header"><span class="title"><a href="$PROFILE_URL">$AUTHOR:</a></span><div>' +
 '<pre id="$ID" class="body">$BODY</pre>' +
 '</div>';

 function showPublishInstructions() {
 var element = document.getElementById('review_instr');
 if (element) {
 element.className = 'opened';
 }
 }
 function revsOnLoadHandler() {
 // register our source container with the commenting code
 var paths = {'svn82': '/trunk/Controller/DataBase/script.SQL'}
 CR_setup('', 'p', 'filescontrol', '', 'svn93', paths,
 'b8b0f64c47b06eae0c45d2f2a738c564', CR_BrowseIntegrationFactory);
 // register our hidden ui elements with the code commenting code ui builder.
 CR_registerLayoutElement('form', form);
 CR_registerLayoutElement('draft_comment', draft_comment);
 CR_registerLayoutElement('published_comment', published_comment);
 
 // register our source container with the commenting code
 // in this case we're registering the container and the revison
 // associated with the contianer which may be the primary revision
 // or may be a previous revision against which the primary revision
 // of the file is being compared.
 CR_registerSourceContainer(document.getElementById('lines'), 'svn82');
 
 CR_registerActivityListener(CR_ACTIVITY_TYPE.REVEAL_DRAFT_PLATE, showPublishInstructions);
 
 CR_registerActivityListener(CR_ACTIVITY_TYPE.REVEAL_PUB_PLATE, pubRevealed);
 CR_registerActivityListener(CR_ACTIVITY_TYPE.REVEAL_DRAFT_PLATE, draftRevealed);
 CR_registerActivityListener(CR_ACTIVITY_TYPE.DISCARD_DRAFT_COMMENT, draftDestroyed);
 
 
 
 
 
 
 
 
 
 var initilized = true;
 reloadCursors();
 }
 window.onload = function() {keysOnLoadHandler(); revsOnLoadHandler();};
</script>
<script type="text/javascript" src="http://www.gstatic.com/codesite/ph/1274223301709965370/js/dit_scripts_20081013.js"></script>

 
 
 <script type="text/javascript" src="http://www.gstatic.com/codesite/ph/1274223301709965370/js/core_scripts_20081103.js"></script>
 <script type="text/javascript" src="/js/codesite_product_dictionary_ph.pack.04102009.js"></script>
 </div>
<div id="footer" dir="ltr">
 
 <div class="text">
 
 &copy;2010 Google -
 <a href="/projecthosting/terms.html">Terms</a> -
 <a href="http://www.google.com/privacy.html">Privacy</a> -
 <a href="/p/support/">Project Hosting Help</a>
 
 </div>
</div>

 <div class="hostedBy" style="margin-top: -20px;">
 <span style="vertical-align: top;">Powered by <a href="http://code.google.com/projecthosting/">Google Project Hosting</a></span>
 </div>
 
 


 
 </body>
</html>

